name: Changelog Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  # push:
  #   branches: [main]

jobs:
  changelog_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Changelog
        run: |
          if ! git diff --name-only HEAD^..HEAD | grep -q 'CHANGELOG.md'; then
            echo "::error::CHANGELOG.md not modified!"
            exit 1
          fi
