name: Check Changelog on PR

on:
  pull_request:

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Check Changelog
      run: |
        CHANGELOG_FILE="CHANGELOG.md"
        HEAD_REF=$(echo $GITHUB_REF | cut -d'/' -f3)

        # Check if the CHANGELOG file exists
        if [ ! -f "$CHANGELOG_FILE" ]; then
          echo "Error: $CHANGELOG_FILE does not exist"
          exit 1
        fi

        # Get the SHA of the latest commit in the branch
        COMMIT_SHA=$(git rev-parse HEAD)

        # Get the SHA of the latest commit in the CHANGELOG file
        CHANGELOG_COMMIT_SHA=$(git log -n 1 --pretty=format:"%H" -- $CHANGELOG_FILE)

        # Check if the CHANGELOG file has been updated in the branch
        if [ "$COMMIT_SHA" != "$CHANGELOG_COMMIT_SHA" ]; then
          echo "Error: $CHANGELOG_FILE has not been updated in the branch $HEAD_REF"
          exit 1
        fi

        echo "Changelog has been updated in the branch $HEAD_REF"
