name: Update package version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the source branch name
        id: get_source_branch_name
        run: echo ::set-output name=branch::${{ github.event.pull_request.head.ref }}
      
      - name: Update package version
        run: |
          BRANCH_NAME="${{ steps.get_source_branch_name.outputs.branch }}"
          if [[ $BRANCH_NAME == break/* ]]; then
            npm version major --no-git-tag-version
          elif [[ $BRANCH_NAME == feat/* ]]; then
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi

      - name: Commit version update
        run: |
          git config --global user.email "amine.abdelli@outlook.fr"
          git config --global user.name "amine-abdelli"
          git commit -am "chore(release): update package version [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.base.ref }}
          force: true
