name: Update package.json version on merge to develop

on:
  pull_request:
    types: [closed]
    branches:
      - ci-test

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine version bump
      id: version-bump
      run: |
        if [[ ${{ github.head_ref }} == feat/* ]]; then
          echo "::set-output name=bump::minor"
        elif [[ ${{ github.head_ref }} == docs/* || ${{ github.head_ref }} == fix/* || ${{ github.head_ref }} == refactor/* || ${{ github.head_ref }} == test/* ]]; then
          echo "::set-output name=bump::patch"
        fi

    - name: Update package.json version
      run: |
        current_version=$(jq -r '.version' package.json)
        new_version=$(npm version --no-git-tag-version ${{ steps.version-bump.outputs.bump }})
        jq --arg new_version "$new_version" '.version = $new_version' package.json > package.tmp.json && mv package.tmp.json package.json
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add package.json
        git commit -m "chore(CI): Update version to $new_version"
        git push
