name: Update package.json version on merge to develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine version bump
      id: version-bump
      run: |
        if [[ ${{ github.head_ref }} == feat/* ]]; then
          echo "::set-output name=bump::minor"
        elif [[ ${{ github.head_ref }} == docs/* || ${{ github.head_ref }} == fix/* || ${{ github.head_ref }} == refactor/* || ${{ github.head_ref }} == test/* ]]; then
          echo "::set-output name=bump::patch"
        fi

    - name: Update package.json version
      run: |
        npm install
        current_version=$(node -p "require('./package.json').version")
        new_version=$(npm version --no-git-tag-version ${{ steps.version-bump.outputs.bump }})
        node -e "const fs = require('fs'); const package = require('./package.json'); package.version = '$new_version'; fs.writeFileSync('./package.json', JSON.stringify(package, null, 2));"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add package.json
        git commit -m "Update version to $new_version"
        git push
